'use client';
import {useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import * as T from 'three';
import {makeLooseProp,animateLoose} from '../brain-room/lib/loose-props';
/** Non-level pages get the same physical toys in a transparent tabletop. */
export default function LooseObjects(){const ref=useRef<HTMLDivElement>(null),path=usePathname(),[active,setActive]=useState(false),[grab,setGrab]=useState(false);const grabRef=useRef(false);grabRef.current=grab;
 useEffect(()=>{const mount=ref.current;if(!mount)return;let renderer:T.WebGLRenderer|null=null,scene:T.Scene,camera:T.PerspectiveCamera,frame=0,time=0,wind=1,brightness=1,quality=1.5;const bodies:{mesh:T.Group;v:T.Vector3;r:number}[]=[];let held:typeof bodies[number]|null=null,last=new T.Vector3();const ray=new T.Raycaster(),pointer=new T.Vector2();
 const size=()=>{if(!renderer)return;renderer.setSize(mount.clientWidth,mount.clientHeight);camera.aspect=mount.clientWidth/mount.clientHeight;camera.updateProjectionMatrix();};
 const init=()=>{if(renderer)return;renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,quality));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=brightness;mount.appendChild(renderer.domElement);scene=new T.Scene();camera=new T.PerspectiveCamera(45,1,.1,100);camera.position.set(0,3,9);camera.lookAt(0,1,0);scene.add(new T.HemisphereLight(0xe8d6ff,0x68468b,3));const light=new T.DirectionalLight(0xffe9bb,4);light.position.set(3,6,5);scene.add(light);size();const clock=new T.Clock();const tick=()=>{frame=requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.04);time+=dt*wind;for(const b of bodies){if(b===held)continue;b.v.y-=9*dt;b.mesh.position.addScaledVector(b.v,dt);if(b.mesh.position.y<b.r-1){b.mesh.position.y=b.r-1;b.v.y=Math.abs(b.v.y)*.45;b.v.x*=.88;b.v.z*=.88;}if(Math.abs(b.mesh.position.x)>4){b.mesh.position.x=T.MathUtils.clamp(b.mesh.position.x,-4,4);b.v.x*=-.6;}b.mesh.rotation.x+=b.v.length()*dt*.5;animateLoose(b.mesh,time,dt,b.v.length());}renderer!.render(scene,camera);};tick();};
 const dispose=(mesh:T.Object3D)=>{mesh.removeFromParent();const gs=new Set<T.BufferGeometry>(),ms=new Set<T.Material>(),ts=new Set<T.Texture>();mesh.traverse(o=>{if(o instanceof T.Mesh){gs.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{ms.add(m);Object.values(m).forEach(v=>{if(v instanceof T.Texture)ts.add(v);});});}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());};
 const settings=(e:Event)=>{const d=(e as CustomEvent).detail;wind=d.wind;brightness=d.light;quality=d.quality;if(renderer){renderer.toneMappingExposure=brightness;renderer.setPixelRatio(Math.min(devicePixelRatio,quality));}};
 const spawn=(event:Event)=>{const e=event as CustomEvent<{kind:string}>;queueMicrotask(()=>{if(e.defaultPrevented)return;init();setActive(true);const mesh=makeLooseProp(e.detail.kind);mesh.position.set((Math.random()-.5)*4,4,0);scene.add(mesh);bodies.push({mesh,v:new T.Vector3((Math.random()-.5)*2,0,0),r:mesh.userData.radius||.25});if(bodies.length>32){const old=bodies.shift()!;dispose(old.mesh);}});};
 const locate=(e:PointerEvent)=>{const b=mount.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);return ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,0,1),0),new T.Vector3());};
 const down=(e:PointerEvent)=>{if(!renderer||!grabRef.current)return;locate(e);const hit=ray.intersectObjects(bodies.map(b=>b.mesh),true)[0];if(hit){held=bodies.find(b=>{let p:T.Object3D|null=hit.object;while(p){if(p===b.mesh)return true;p=p.parent;}return false;})||null;if(held){last.copy(held.mesh.position);mount.setPointerCapture(e.pointerId);}}};const move=(e:PointerEvent)=>{if(!held)return;const p=locate(e);if(p){held.v.copy(p).sub(last).multiplyScalar(20).clampLength(0,16);held.mesh.position.copy(p);last.copy(p);}};const up=()=>held=null;
 const clear=()=>{bodies.forEach(b=>dispose(b.mesh));bodies.length=0;held=null;setActive(false);};window.addEventListener('trip-world-settings',settings);window.dispatchEvent(new Event('trip-world-ready'));window.addEventListener('trip-world-spawn',spawn);window.addEventListener('trip-world-clear',clear);window.addEventListener('resize',size);mount.addEventListener('pointerdown',down);mount.addEventListener('pointermove',move);mount.addEventListener('pointerup',up);mount.addEventListener('pointercancel',up);
 return()=>{cancelAnimationFrame(frame);window.removeEventListener('trip-world-settings',settings);window.removeEventListener('trip-world-spawn',spawn);window.removeEventListener('trip-world-clear',clear);window.removeEventListener('resize',size);mount.removeEventListener('pointerdown',down);mount.removeEventListener('pointermove',move);mount.removeEventListener('pointerup',up);mount.removeEventListener('pointercancel',up);if(scene)scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});renderer?.dispose();renderer?.domElement.remove();setActive(false);};},[path]);
 return <><div ref={ref} className="world-object-layer" style={{pointerEvents:active&&grab?'auto':'none'}}/>{active&&<button className="world-object-grab" onClick={()=>setGrab(v=>!v)}>{grab?'Release screen · keep toys':'Grab & throw toys'}</button>}</>;
}
