'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {createPortal} from 'react-dom';
import {usePathname} from 'next/navigation';
import dynamic from 'next/dynamic';
import './world-tools.css';
const LooseObjects=dynamic(()=>import('./LooseObjects'),{ssr:false});
type Category='customize'|'spawn';
const ToolContext=createContext<{hosts:Record<Category,HTMLDivElement|null>;open:(c:Category)=>void}>({hosts:{customize:null,spawn:null},open:()=>{}});
export function ToolsSection({category='customize',title,children}:{category?:Category;title:string;children:ReactNode}){const {hosts}=useContext(ToolContext);return hosts[category]?createPortal(<section className="world-tool-section"><h3>{title}</h3>{children}</section>,hosts[category]!):null;}
export function FloatingPanel({title,open,onClose,children,side=0,initialHeight=560}:{title:string;open:boolean;onClose:()=>void;children:ReactNode;side?:number;initialHeight?:number}){
 const [dimensions,setDimensions]=useState({w:410,h:initialHeight});const resizing=useRef<{x:number;y:number;w:number;h:number}|null>(null);
 const [pos,setPos]=useState({x:18+side*440,y:130}),[scale,setScale]=useState(1);const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);const ref=useRef<HTMLElement>(null);
 useEffect(()=>{const fit=()=>{const width=Math.min(dimensions.w,innerWidth-30),nextScale=Math.min(scale,(innerWidth-38)/width);setScale(nextScale);setPos(p=>({x:Math.min(p.x,Math.max(8,innerWidth-width*nextScale-16)),y:Math.min(p.y,Math.max(110,innerHeight-180))}));};fit();window.addEventListener('resize',fit);return()=>window.removeEventListener('resize',fit);},[dimensions.w,scale]);
 return <aside ref={ref} className="world-floating-panel" aria-label={title} hidden={!open} style={{left:pos.x,top:pos.y,width:dimensions.w,height:dimensions.h,transform:`scale(${scale})`,'--panel-scale':scale} as CSSProperties}>
 <button className="world-close-bubble" aria-label={`Close ${title}`} onClick={onClose}>×</button><header className="world-drag-handle" onPointerDown={e=>{if((e.target as HTMLElement).closest('button,input'))return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,px:pos.x,py:pos.y};}} onPointerMove={e=>{const d=drag.current;if(d)setPos({x:Math.max(6,Math.min(innerWidth-Math.min(dimensions.w,innerWidth-30)*scale-14,d.px+e.clientX-d.x)),y:Math.max(100,Math.min(innerHeight-80,d.py+e.clientY-d.y))});}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><span>⠿</span><h2>{title}</h2><small>DRAG</small></header>
 <div className="world-panel-content">{children}</div><footer><label>Panel size <input aria-label={`${title} panel scale`} type="range" min="0.75" max="1.3" step="0.05" value={scale} onChange={e=>setScale(+e.target.value)}/></label><button onClick={()=>{setPos({x:18,y:130});setScale(1);setDimensions({w:410,h:initialHeight});}}>Reset panel</button><button className="world-resize-handle" aria-label={`Resize ${title}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);resizing.current={x:e.clientX,y:e.clientY,w:ref.current?.clientWidth||410,h:ref.current?.clientHeight||560};}} onPointerMove={e=>{const r=resizing.current;if(r)setDimensions({w:Math.max(280,Math.min(innerWidth-30,r.w+(e.clientX-r.x)/scale)),h:Math.max(220,Math.min(innerHeight-150,r.h+(e.clientY-r.y)/scale))});}} onPointerUp={()=>resizing.current=null} onPointerCancel={()=>resizing.current=null}>↘ resize</button></footer></aside>;
}
export const CAN_SPAWNS=[['yoohoo','Yoo-hoo'],['pepsi','Pepsi'],['monster','Monster'],['rat-meat','Rat meat'],['rat-meat-silver','Silver rat meat'],['rat-meat-gold','Gold rat meat']];
export const ORGAN_SPAWNS=[['brain','Brain'],['lungs','Lungs'],['heart','Heart'],['liver','Liver'],['bones','Bones'],['stomach','Stomach + throat'],['dentures','Dentures'],['eyes','Eyeballs']];
export function spawnWorldItem(kind:string){window.dispatchEvent(new CustomEvent('trip-world-spawn',{detail:{kind},cancelable:true}));}
export default function WorldTools({children}:{children:ReactNode}){
 const path=usePathname();const [customize,setCustomize]=useState(false),[spawn,setSpawn]=useState(false),[customHost,setCustomHost]=useState<HTMLDivElement|null>(null),[spawnHost,setSpawnHost]=useState<HTMLDivElement|null>(null),[wind,setWind]=useState(1),[light,setLight]=useState(1),[quality,setQuality]=useState(1.5);
 useEffect(()=>{const send=()=>window.dispatchEvent(new CustomEvent('trip-world-settings',{detail:{wind,light,quality}}));send();window.addEventListener('trip-world-ready',send);return()=>window.removeEventListener('trip-world-ready',send);},[wind,light,quality,path]);
 useEffect(()=>{setCustomize(false);setSpawn(false);},[path]);useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setCustomize(false);setSpawn(false);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 return <ToolContext.Provider value={{hosts:{customize:customHost,spawn:spawnHost},open:c=>c==='customize'?setCustomize(true):setSpawn(true)}}>
 <nav className="world-orange-ribbon" aria-label="World tools"><a href="/" aria-label="Home">↖ HOME</a><b>{path==='/'?'TRIPTOTROPIC':path.startsWith('/brain-room')?'BRAIN WORLD':path.startsWith('/urf')?'PLANET URF':'TRIPTOTROPIC'}</b><div><button aria-expanded={customize} onClick={()=>setCustomize(v=>!v)}>✧ Customize</button><button aria-expanded={spawn} onClick={()=>setSpawn(v=>!v)}>＋ Spawn shit</button></div></nav>
 <FloatingPanel title="Customize" open={customize} onClose={()=>setCustomize(false)}><div ref={setCustomHost}/><section className="world-tool-section"><h3>Atmosphere & graphics</h3><label>Wind & breathing <input type="range" min="0" max="2" step=".1" value={wind} onChange={e=>setWind(+e.target.value)}/></label><label>Brightness <input type="range" min=".55" max="1.8" step=".05" value={light} onChange={e=>setLight(+e.target.value)}/></label><label>Resolution <select value={quality} onChange={e=>setQuality(+e.target.value)}><option value="1">Balanced</option><option value="1.5">High</option><option value="2">Ultra</option></select></label></section><section className="world-tool-section"><h3>Explore</h3><div className="world-button-grid"><a href="/brain-room">Brain world</a><a href="/brain-room?arrival=field">Cow field</a><a href="/brain-room?arrival=lab">Bongo's lab</a><a href="/urf-3d/editor">Urf archer</a><a href="/assets-room">Assets room</a><a href="/map">World map</a></div></section></FloatingPanel>
 <FloatingPanel title="Spawn shit" open={spawn} onClose={()=>setSpawn(false)} side={1}><div ref={setSpawnHost}/><section className="world-tool-section"><h3>Cans</h3><div className="world-button-grid">{CAN_SPAWNS.map(([id,label])=><button key={id} onClick={()=>spawnWorldItem(id)}>{label}</button>)}</div></section><section className="world-tool-section"><h3>Organs</h3><div className="world-button-grid">{ORGAN_SPAWNS.map(([id,label])=><button key={id} onClick={()=>spawnWorldItem(id)}>{label}</button>)}</div></section><section className="world-tool-section"><h3>Odds & ends</h3><div className="world-button-grid"><button onClick={()=>spawnWorldItem('rock')}>Rock</button><button onClick={()=>spawnWorldItem('worm')}>Worm</button><button onClick={()=>window.dispatchEvent(new CustomEvent('trip-world-clear'))}>Clear loose objects</button></div><p>Brain world: F picks up / drops · Click throws or hits · Hold click to charge a throw.</p></section></FloatingPanel>
 {children}<LooseObjects/></ToolContext.Provider>;
}
