import * as T from 'three';
import {mergeGeometries} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
export type BrainSurface=(direction:T.Vector3)=>{point:T.Vector3;normal:T.Vector3};
export function cortexShell(surface:BrainSurface,options:{count?:number;radius?:number;detail?:number;segments?:number;radial?:number;skip?:(point:T.Vector3)=>boolean}={}){
 const root=new T.Group();root.name='Organic cortical shell';const material=new T.MeshPhysicalMaterial({color:0xe0b0a6,roughness:.44,clearcoat:.32,sheen:.2});
 material.name='Cortex tissue';
 if(typeof document!=='undefined'){const texture=new T.TextureLoader().load('/brain-room/cortex.png');texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=8;material.map=material.bumpMap=texture;material.bumpScale=.012;}
 const baseGeo=new T.IcosahedronGeometry(1,options.detail??54),p=baseGeo.getAttribute('position'),uv=baseGeo.getAttribute('uv'),positions:number[]=[],uvs:number[]=[];
 for(let i=0;i<p.count;i+=3){const points=[0,1,2].map(j=>surface(new T.Vector3().fromBufferAttribute(p,i+j).normalize()).point);if(options.skip?.(points[0].clone().add(points[1]).add(points[2]).divideScalar(3)))continue;for(let j=0;j<3;j++){positions.push(...points[j].toArray());uvs.push(uv.getX(i+j)*2,uv.getY(i+j)*2);}}
 baseGeo.dispose();const base=new T.BufferGeometry();base.setAttribute('position',new T.Float32BufferAttribute(positions,3));base.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));base.computeVertexNormals();const recess=material.clone();recess.name='Cortex recesses';recess.color.setHex(0xb88d89);root.add(new T.Mesh(base,recess));
 const tubes:T.BufferGeometry[]=[];const count=options.count??540,radius=options.radius??.037;
 for(let i=0;i<count;i++){const y=1-2*(i+.5)/count,phi=i*2.39996323,d=new T.Vector3(Math.sqrt(1-y*y)*Math.cos(phi),y,Math.sqrt(1-y*y)*Math.sin(phi)),up=new T.Vector3(0,1,0),u=new T.Vector3().crossVectors(d,Math.abs(y)>.9?new T.Vector3(1,0,0):up).normalize().applyAxisAngle(d,Math.sin(i*127.1)*Math.PI),v=new T.Vector3().crossVectors(d,u).normalize();const points:T.Vector3[]=[];
  for(let j=0;j<13;j++){const t=(j/12-.5),a=i%4===0?Math.cos(t*Math.PI*3.1+i)*(.07+(t+.5)*.1):t*.56,b=i%4===0?Math.sin(t*Math.PI*3.1+i)*(.07+(t+.5)*.1):Math.sin(t*15+i*1.8)*.065+Math.sin(t*23+i)*.014;const direction=d.clone().addScaledVector(u,a).addScaledVector(v,b).normalize(),s=surface(direction);points.push(s.point.addScaledVector(s.normal,radius*.2));}
  if(points.some(p=>options.skip?.(p)))continue;const curve=new T.CatmullRomCurve3(points),tube=new T.TubeGeometry(curve,options.segments??38,radius*(.86+.15*Math.sin(i)),options.radial??10,false);const uv=tube.getAttribute('uv');for(let j=0;j<uv.count;j++)uv.setX(j,uv.getX(j)*curve.getLength()/1.6);tubes.push(tube);
 }
 const geometry=mergeGeometries(tubes);tubes.forEach(g=>g.dispose());if(geometry)root.add(new T.Mesh(geometry,material));root.traverse(o=>{if(o instanceof T.Mesh)o.castShadow=o.receiveShadow=true;});return root;
}
export function brainEnvelope(direction:T.Vector3){const lobes=[-1,1].map(side=>({center:new T.Vector3(side*.52,.12,-.04),axes:new T.Vector3(.9676,1.2036,1.3924)}));let distance=0,chosen=lobes[0];for(const lobe of lobes){const d=direction.clone().divide(lobe.axes),c=lobe.center.clone().divide(lobe.axes),a=d.dot(d),b=d.dot(c),det=b*b-a*(c.dot(c)-1);if(det>=0){const t=(b+Math.sqrt(det))/a;if(t>distance){distance=t;chosen=lobe;}}}const point=direction.clone().multiplyScalar(distance);return {point,normal:point.clone().sub(chosen.center).divide(chosen.axes).divide(chosen.axes).normalize()};}
export function makeDreamTree(index:number){const root=new T.Group();root.name='Swaying dream tree';const bark=new T.MeshStandardMaterial({color:index%2?0x684460:0x4a4653,roughness:.83}),leaf=new T.MeshPhysicalMaterial({color:index%3?0x6c9972:0x8280a5,roughness:.7,sheen:.5});const h=4+(index%3)*.65;const curve=new T.CatmullRomCurve3([new T.Vector3(),new T.Vector3(.25,h*.35,.12),new T.Vector3(-.18,h*.7,0),new T.Vector3(.25,h,0)]);root.add(new T.Mesh(new T.TubeGeometry(curve,36,.19,14,false),bark));for(let i=0;i<7;i++){const a=i*2.4,end=new T.Vector3(Math.cos(a)*1.9,h-.7+Math.sin(i)*.6,Math.sin(a)*1.7);root.add(new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3([curve.getPoint(.6),end.clone().multiplyScalar(.7).add(new T.Vector3(0,1,0)),end]),20,.07,10,false),bark));const crown=new T.Mesh(new T.SphereGeometry(1,28,18),leaf);crown.position.copy(end);crown.scale.set(1.1,.63,.95);root.add(crown);}root.traverse(o=>{if(o instanceof T.Mesh)o.castShadow=o.receiveShadow=true;});return root;}
