import * as T from 'three';
export const WORM_COLORS=[0xe997b5,0xe997b5,0xf2b4c6,0xdd829d,0xef9eb8,0xbe82ff,0x79e59b,0x75b9ff,0xf2cc68,0xec6376];
const MAX_HOLES=24;
/** One deformation field drives both the visible cortex and crawler contact. */
export function makeLivingSkin(amplitude=.045,frequency=5){
 const time={value:0},holes={value:Array.from({length:MAX_HOLES},()=>new T.Vector4(0,0,0,0))},normals={value:Array.from({length:MAX_HOLES},()=>new T.Vector3(0,1,0))};
 const offset=(p:T.Vector3)=>new T.Vector3(Math.sin(p.y*frequency+Math.sin(p.z*frequency*.7+time.value)*.8+time.value*1.3),Math.sin(p.z*frequency*.91+Math.sin(p.x*frequency*.8-time.value)*.7+time.value*1.1),Math.sin(p.x*frequency*.83+Math.sin(p.y*frequency*.6+time.value)*.8-time.value*1.2)).multiplyScalar(amplitude);
 const delta=(p:T.Vector3)=>{const d=offset(p);for(let i=0;i<MAX_HOLES;i++){const h=holes.value[i];if(h.w<=0)continue;const q=p.clone().sub(new T.Vector3(h.x,h.y,h.z)),n=normals.value[i],height=q.dot(n);if(Math.abs(height)>h.w*2+.3)continue;q.addScaledVector(n,-height);const r=q.length();if(r>1e-5&&r<h.w*1.8)d.addScaledVector(q,(h.w*1.8-r)*.48/r);}return d;};
 const sample=(point:T.Vector3,normal:T.Vector3)=>{const tangent=new T.Vector3().crossVectors(normal,Math.abs(normal.y)>.9?new T.Vector3(1,0,0):new T.Vector3(0,1,0)).normalize(),bitangent=new T.Vector3().crossVectors(normal,tangent),p=point.clone().add(delta(point)),a=point.clone().addScaledVector(tangent,.005),b=point.clone().addScaledVector(bitangent,.005);a.add(delta(a)).sub(p);b.add(delta(b)).sub(p);const n=a.cross(b).normalize();if(n.dot(normal)<0)n.negate();return {point:p,normal:n};};
 const declaration=`uniform float skinTime;uniform float skinAmplitude;uniform float skinFrequency;uniform vec4 skinHoles[${MAX_HOLES}];uniform vec3 skinNormals[${MAX_HOLES}];varying vec3 skinPoint;
 vec3 skinOffset(vec3 p){float f=skinFrequency;float t=skinTime;vec3 d=skinAmplitude*vec3(sin(p.y*f+sin(p.z*f*.7+t)*.8+t*1.3),sin(p.z*f*.91+sin(p.x*f*.8-t)*.7+t*1.1),sin(p.x*f*.83+sin(p.y*f*.6+t)*.8-t*1.2));for(int i=0;i<${MAX_HOLES};i++){vec4 h=skinHoles[i];if(h.w>0.){vec3 q=p-h.xyz;float z=dot(q,skinNormals[i]);q-=skinNormals[i]*z;float r=length(q);if(abs(z)<(h.w*2.+.3)&&r>.00001&&r<h.w*1.8)d+=q*(h.w*1.8-r)*.48/r;}}return d;}`;
 const fragment=`varying vec3 skinPoint;uniform vec4 skinHoles[${MAX_HOLES}];uniform vec3 skinNormals[${MAX_HOLES}];`;
 function patch(material:T.Material){material.onBeforeCompile=shader=>{Object.assign(shader.uniforms,{skinTime:time,skinAmplitude:{value:amplitude},skinFrequency:{value:frequency},skinHoles:holes,skinNormals:normals});shader.vertexShader=declaration+'\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','vec3 transformed=position+skinOffset(position);skinPoint=position;');shader.fragmentShader=fragment+'\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('void main() {',`void main() {for(int i=0;i<${MAX_HOLES};i++){vec4 h=skinHoles[i];if(h.w>0.){vec3 q=skinPoint-h.xyz;float z=dot(q,skinNormals[i]);if(abs(z)<(h.w*2.+.3)&&length(q-skinNormals[i]*z)<h.w*.83)discard;}}`);};material.customProgramCacheKey=()=>`living-cortex-${amplitude}-${frequency}`;material.needsUpdate=true;}
 function apply(mesh:T.Mesh){for(const material of Array.isArray(mesh.material)?mesh.material:[mesh.material])patch(material);const depth=new T.MeshDepthMaterial({depthPacking:T.RGBADepthPacking}),distance=new T.MeshDistanceMaterial();patch(depth);patch(distance);mesh.customDepthMaterial=depth;mesh.customDistanceMaterial=distance;mesh.frustumCulled=false;}
 return {time,holes,normals,amplitude,sample,delta,apply,clear(){holes.value.forEach(h=>h.w=0);},opening(index:number,point:T.Vector3,normal:T.Vector3,radius:number){if(index>=MAX_HOLES)return;holes.value[index].set(point.x,point.y,point.z,radius);normals.value[index].copy(normal);}};
}
export type LivingSkin=ReturnType<typeof makeLivingSkin>;
