import {gravityAcceleration} from '../../world/physics';
import {makeSpecimen,type SpecimenKind} from './specimens';
import * as T from 'three';
import {makeLooseProp,animateLoose,CAN_LABELS,ORGAN_KINDS} from './loose-props';
import {collide,type makeLevel} from './level';
import {Ragdoll} from './ragdoll';
type Body={mesh:T.Group;p:T.Vector3;v:T.Vector3;spin:T.Vector3;r:number;kind:string;age:number;survivor:boolean;food:boolean};
type Feast={position:T.Vector3;age:number;worms:T.Group[];holes:T.Mesh[];food:Body[]};
function disposeTree(root:T.Object3D){root.removeFromParent();const gs=new Set<T.BufferGeometry>(),ms=new Set<T.Material>(),ts=new Set<T.Texture>();root.traverse(o=>{if(o instanceof T.Mesh){gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){ms.add(m);for(const v of Object.values(m))if(v instanceof T.Texture)ts.add(v);}}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());}
export class Playground{
 bodies:Body[]=[];held:Body|null=null;ragdolls:Ragdoll[]=[];feasts:Feast[]=[];time=0;notice='F picks up · Click hits';ragHeld:Ragdoll|null=null;
 constructor(public scene:T.Scene,public level:ReturnType<typeof makeLevel>,public player:()=>{p:T.Vector3;creature:T.Group|null;camera:T.Camera}){}
 spawn(kind:string,at?:T.Vector3,velocity?:T.Vector3){const {p,camera}=this.player(),dir=camera.getWorldDirection(new T.Vector3());dir.y=0;dir.normalize();const mesh=makeLooseProp(kind);const position=at?.clone()||p.clone().addScaledVector(dir,1.65).add(new T.Vector3(0,.9,0));mesh.position.copy(position);this.scene.add(mesh);const body:Body={mesh,p:mesh.position,v:velocity?.clone()||new T.Vector3(0,1.5,0),spin:new T.Vector3(Math.random()*3,Math.random()*3,Math.random()*3),r:mesh.userData.radius||.25,kind,age:0,survivor:false,food:false};this.bodies.push(body);if(this.bodies.length>64){const old=this.bodies.find(b=>b!==this.held&&!b.survivor);if(old)this.remove(old);}return body;}
 remove(body:Body){disposeTree(body.mesh);const i=this.bodies.indexOf(body);if(i>=0)this.bodies.splice(i,1);if(this.held===body)this.held=null;}
 spawnSubject(kind:SpecimenKind){const chair=makeSpecimen(kind,0),animal=chair.userData.animal as T.Group;animal.removeFromParent();animal.position.copy(this.player().p).add(new T.Vector3(1,1,-2));this.scene.add(animal);animal.updateMatrixWorld(true);const rag=new Ragdoll(animal,this.scene,new T.Vector3(0,2,0));this.ragdolls.push(rag);if(this.ragdolls.length>12){disposeTree(this.ragdolls.shift()!.root);}return rag;}
 pickup(){if(this.held){this.held.v.set(0,0,0);this.held=null;this.notice='Dropped';return;}const p=this.player().p;const nearest=this.bodies.filter(b=>b.p.distanceTo(p)<3).sort((a,b)=>a.p.distanceTo(p)-b.p.distanceTo(p))[0];if(nearest){this.held=nearest;nearest.food=false;this.notice='Hold click to charge · Release to throw';}else this.notice='Move closer to a can, rock, or organ';}
 throw(strength=16){if(!this.held)return;const {camera,creature}=this.player(),dir=creature?new T.Vector3(0,0,1).applyQuaternion(creature.getWorldQuaternion(new T.Quaternion())):camera.getWorldDirection(new T.Vector3());dir.y+=.15;this.held.v.copy(dir.normalize()).multiplyScalar(strength);this.held.spin.set(7,11,4);this.held=null;this.notice='Nice throw';}
 releaseSpecimen(index:number,impulse=new T.Vector3(0,3,0)){const specimen=this.level.lab.specimens[index];if(specimen.userData.released)return;specimen.userData.released=true;const animal=specimen.userData.animal as T.Group;animal.updateMatrixWorld(true);const rag=new Ragdoll(animal,this.scene,impulse);this.ragdolls.push(rag);this.notice='Test subject released · Grab and fling';return rag;}
 punch(ray:T.Raycaster){const {p}=this.player();let nearest:Body|undefined;const hit=ray.intersectObjects(this.bodies.map(b=>b.mesh),true)[0];if(hit&&hit.distance<7){nearest=this.bodies.find(b=>{let o:T.Object3D|null=hit.object;while(o){if(o===b.mesh)return true;o=o.parent;}return false;});if(nearest){nearest.v.copy(ray.ray.direction).multiplyScalar(9);nearest.v.y+=4;this.notice='Bonk';return;}}
 for(let i=0;i<this.level.lab.specimens.length;i++){const m=this.level.lab.specimens[i];if(!m.userData.released&&ray.intersectObject(m,true).some(h=>h.point.distanceTo(p)<4)){this.releaseSpecimen(i,ray.ray.direction.clone().multiplyScalar(7).add(new T.Vector3(0,3,0)));return;}}
 for(const cow of this.level.cows)if(cow.root.visible&&ray.intersectObject(cow.root,true).some(h=>h.point.distanceTo(p)<4)){cow.head.rotation.z=.35;this.notice='Moo?! Try a flying can.';return;}this.notice='Click to hit · F picks up';}
 explodeCow(index:number){const cow=this.level.cows[index];if(!cow.root.visible)return;cow.root.visible=false;const center=cow.root.position.clone().add(new T.Vector3(0,1,0));const food:Body[]=[];for(let i=0;i<9;i++){const b=this.spawn(ORGAN_KINDS[i%ORGAN_KINDS.length],center.clone().add(new T.Vector3((Math.random()-.5)*.5,0,(Math.random()-.5)*.5)),new T.Vector3((Math.random()-.5)*11,4+Math.random()*5,(Math.random()-.5)*11));b.food=i>0;b.survivor=i===0;food.push(b);}const worms:T.Group[]=[],holes:T.Mesh[]=[];for(let i=0;i<5;i++){const a=i/5*Math.PI*2,pos=center.clone().add(new T.Vector3(Math.cos(a)*3,-1,Math.sin(a)*3));const hole=new T.Mesh(new T.CircleGeometry(.27,32),new T.MeshBasicMaterial({color:0x170e20,side:T.DoubleSide}));hole.rotation.x=-Math.PI/2;hole.position.copy(pos);hole.position.y=.012;this.scene.add(hole);holes.push(hole);const worm=makeLooseProp('worm');worm.position.copy(hole.position);worm.visible=false;this.scene.add(worm);worms.push(worm);}this.feasts.push({position:center,age:0,worms,holes,food});this.notice='The cleanup crew heard that. One brain is yours to keep.';}
 hand(){const {p,creature,camera}=this.player();if(!creature)return p.clone().add(new T.Vector3(0,1,0));if(creature.userData.kind==='rat'){const tail=creature.userData.tail as T.Group[];tail.forEach((b,i)=>{b.rotation.x=.21;b.rotation.y=Math.sin(i*.4)*.025;});creature.updateMatrixWorld(true);return tail.at(-1)!.localToWorld(new T.Vector3(0,0,-.04));}const limbs=creature.userData.limbs as T.Group[];limbs[4].rotation.x=-1.05;limbs[5].rotation.x=-.45;creature.updateMatrixWorld(true);return limbs[5].localToWorld(new T.Vector3(0,-.72,.08));}
 update(dt:number){this.time+=dt;if(this.held){const goal=this.hand();this.held.v.copy(goal).sub(this.held.p).multiplyScalar(1/Math.max(dt,.001));this.held.p.copy(goal);}for(const rag of this.ragdolls)rag.step(dt,this.level.solids);
 for(const body of [...this.bodies]){body.age+=dt;if(body===this.held){animateLoose(body.mesh,this.time,dt,2);continue;}const speed=body.v.length();const steps=Math.max(1,Math.ceil(speed*dt/.15));for(let step=0;step<steps;step++){const h=dt/steps;body.v.y-=gravityAcceleration()*h;body.p.addScaledVector(body.v,h);const broken=[...this.level.barnWalls.hit(body.p,body.r,speed),...this.level.lab.breakables.hit(body.p,body.r,speed)];if(broken.length){for(const [i,piece] of broken.entries()){if(i>6)break;const chip=this.spawn('rock',piece.center,new T.Vector3((Math.random()-.5)*6,2+Math.random()*4,(Math.random()-.5)*6));chip.mesh.userData.baseScale=new T.Vector3(.8,.4,.65);chip.age=40;}body.v.multiplyScalar(.72);this.notice='Wall breached';}
 if(CAN_LABELS[body.kind]&&speed>5)for(let i=0;i<this.level.cows.length;i++){const cow=this.level.cows[i];if(cow.root.visible&&body.p.distanceTo(cow.root.position.clone().add(new T.Vector3(0,1.05,0)))<1.05+body.r){this.explodeCow(i);body.v.multiplyScalar(.5);break;}}
 const before=body.v.clone();const grounded=collide(body.p,body.r,this.level.solids,body.v,.35);if(grounded){body.v.x*=.96;body.v.z*=.96;}if(before.distanceTo(body.v)>.1)body.spin.multiplyScalar(.88);if(Math.abs(body.p.x)>87){body.p.x=T.MathUtils.clamp(body.p.x,-87,87);body.v.x*=-.6;}if(Math.abs(body.p.z)>87){body.p.z=T.MathUtils.clamp(body.p.z,-87,87);body.v.z*=-.6;}}
 body.mesh.rotation.x+=body.spin.x*dt;body.mesh.rotation.y+=body.spin.y*dt;body.spin.multiplyScalar(Math.exp(-dt*.4));animateLoose(body.mesh,this.time,dt,body.v.length());if(body.p.y<-8||body.age>90&&!body.survivor&&!body.food)this.remove(body);}
 // Separate nearby loose bodies so piles bounce instead of passing through each other.
 for(let a=0;a<this.bodies.length;a++)for(let b=a+1;b<this.bodies.length;b++){const A=this.bodies[a],B=this.bodies[b];if(A===this.held||B===this.held)continue;const delta=B.p.clone().sub(A.p),d=delta.length(),r=A.r+B.r;if(d>.001&&d<r){delta.divideScalar(d);A.p.addScaledVector(delta,-(r-d)*.5);B.p.addScaledVector(delta,(r-d)*.5);const v=B.v.clone().sub(A.v).dot(delta);if(v<0){A.v.addScaledVector(delta,v*.65);B.v.addScaledVector(delta,-v*.65);}}}
 for(const feast of [...this.feasts]){feast.age+=dt;if(feast.age>36){feast.worms.forEach(disposeTree);feast.holes.forEach(disposeTree);this.feasts.splice(this.feasts.indexOf(feast),1);continue;}if(feast.age>28)for(const b of feast.food)if(b.food&&this.bodies.includes(b))this.remove(b);if(feast.age<2)continue;feast.worms.forEach((worm,i)=>{worm.visible=feast.age<32;const food=feast.food.filter(b=>b.food&&this.bodies.includes(b));const target=food[i%Math.max(1,food.length)];if(target){const delta=target.p.clone().sub(worm.position);delta.y=0;if(delta.length()>.25)worm.position.addScaledVector(delta.normalize(),dt*1.3);worm.rotation.y=Math.atan2(delta.x,delta.z);if(worm.position.distanceTo(target.p)<.8&&feast.age>6){target.mesh.scale.multiplyScalar(.96);if(feast.age>9+i*.6)this.remove(target);}}else worm.position.lerp(feast.holes[i].position,dt*.9);worm.position.y=.08+Math.sin(this.time*5+i)*.025;animateLoose(worm,this.time+i,dt,2);feast.holes[i].scale.setScalar(Math.min(1,Math.max(0,34-feast.age)));});}
 }
 clear(){[...this.bodies].forEach(b=>this.remove(b));this.held=null;this.feasts.forEach(f=>{f.worms.forEach(disposeTree);f.holes.forEach(disposeTree);});this.feasts=[];}
 repair(){this.level.barnWalls.repair();this.level.lab.breakables.repair();this.level.cows.forEach(c=>c.root.visible=true);this.notice='Buildings restored. Cows restored.';}
}
