'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
export default function BongoConsole({onClose,onUpload}:{onClose:()=>void;onUpload:()=>void}){
 const [messages,setMessages]=useState<{role:'user'|'assistant';content:string}[]>([{role:'assistant',content:'Ook. Welcome to my laboratory. Ask me a question, or step into my extremely distinguished body. Please wash your consciousness first.'}]);
 const [draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[upload,setUpload]=useState(false);const panel=useRef<HTMLDivElement>(null),end=useRef<HTMLDivElement>(null);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[messages,busy]);
 useEffect(()=>{if(!upload)return;const timer=setTimeout(onUpload,1700);return()=>clearTimeout(timer);},[upload,onUpload]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code==='Escape')onClose();if(e.key==='Tab'){const targets=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input');if(!targets?.length)return;const first=targets[0],last=targets[targets.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[onClose]);
 async function send(e:FormEvent){e.preventDefault();const content=draft.trim();if(!content||busy)return;const next=[...messages,{role:'user' as const,content}];setMessages(next);setDraft('');setBusy(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next})});if(!r.ok)throw Error();const data=await r.json();setMessages(m=>[...m,{role:'assistant',content:data.reply||'Ook. Signal scrambled. Try again.'}]);}catch{setMessages(m=>[...m,{role:'assistant',content:'My cortex lost the signal. Try again in a moment. Ook.'}]);}finally{setBusy(false);}}
 return <div className="bongo-console-shade"><div ref={panel} className="bongo-world-console" role="dialog" aria-modal="true" aria-labelledby="bongo-console-title"><header><div><small>BONGO / SUPERCOMPUTER</small><h2 id="bongo-console-title">Talk to the ape <span>:)</span></h2></div><button onClick={onClose} aria-label="Close computer">×</button></header><div className="bongo-world-transcript" aria-live="polite" aria-busy={busy}>{messages.map((m,i)=><article className={m.role} key={i}><b>{m.role==='user'?'YOU':'DR. BONGO'}</b><p>{m.content}</p></article>)}{busy&&<p>Neurons firing…</p>}<div ref={end}/></div><form onSubmit={send}><label htmlFor="bongo-message">Message to cortex</label><div><input autoFocus id="bongo-message" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={600} placeholder="Bananas, the universe, anything…"/><button disabled={busy||!draft.trim()}>Send</button></div></form><button className="bongo-upload" disabled={upload} onClick={()=>setUpload(true)}>{upload?'UPLOADING… WIGGLE YOUR NEW FINGERS.':'Upload consciousness → Play as Dr. Bongo'}</button></div></div>;
}
