export type LibraryBook={id:string;title:string;subtitle:string;file:string;kind:'html'|'pdf';source:string;note:string};
export const LIBRARY_BOOKS:LibraryBook[]=[
{id:'solomon',title:'The Lesser Key of Solomon',subtitle:'Goetia · 1916 edition',file:'/library/solomon/index.html',kind:'html',source:'https://www.gutenberg.org/ebooks/72679',note:'Complete public-domain Goetia edition, including its diagrams. This edition is not the entire five-part Lemegeton.'},
{id:'necronomicon',title:'The Necronomicon shelf',subtitle:'Lovecraft fiction & companion',file:'/library/necronomicon/companion.html',kind:'html',source:'https://www.gutenberg.org/ebooks/68283',note:'A clearly labeled companion plus the complete 1928 Call of Cthulhu. The fictional Necronomicon has no authentic ancient full text; modern commercial editions are not reproduced.'},
{id:'enoch',title:'The Book of Enoch',subtitle:'R. H. Charles · 1917 translation',file:'/library/enoch/index.html',kind:'html',source:'https://www.gutenberg.org/ebooks/77935',note:'Complete public-domain translation and editorial apparatus.'},
{id:'illuminati',title:'Illuminati: the historical record',subtitle:'Primary source & research notebook',file:'/library/illuminati/companion.html',kind:'html',source:'https://www.gutenberg.org/ebooks/47605',note:'Robison’s 1797 polemic is included as a historical source, not as proof of modern claims.'},
{id:'mkultra',title:'MKULTRA',subtitle:'The 1977 Senate hearing',file:'/library/mkultra/manifest.json',kind:'pdf',source:'https://www.intelligence.senate.gov/wp-content/uploads/2024/08/sites-default-files-hearings-95mkultra.pdf',note:'Complete 173-page official hearing, split into readable volumes with original page images.'},
{id:'wwii',title:'The Doctors’ Trial',subtitle:'Nuremberg · Medical Case, Volume II',file:'/library/wwii/index.html',kind:'html',source:'https://www.loc.gov/item/2011525364/',note:'Complete official Volume II from the Medical Case, including judgments and the Nuremberg Code. Historical evidence of abusive experiments, not an endorsement.'},
{id:'programming',title:'From First Line to Your Own World',subtitle:'An AI-era programming workbook',file:'/library/programming/index.html',kind:'html',source:'https://developer.mozilla.org/en-US/docs/Learn_web_development',note:'Original Triptotropic workbook: foundations, exercises, debugging, 3D, testing, and a practical path toward professional work.'},
{id:'flight',title:'Learning to Fly',subtitle:'FAA Airplane Flying Handbook',file:'/library/flight/manifest.json',kind:'pdf',source:'https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/airplane_handbook',note:'Complete FAA-H-8083-3C handbook, including illustrations. A study reference used with qualified flight instruction and the aircraft’s approved handbook.'},
{id:'occult',title:'Ritual, Charms & the Golden Bough',subtitle:'Two complete historical folklore volumes',file:'/library/occult/companion.html',kind:'html',source:'https://www.gutenberg.org/ebooks/3623',note:'A historical collection of ritual and folklore. Its dated interpretations are not a modern scientific consensus or proof of supernatural effects.'},
{id:'frankenstein',title:'Frankenstein',subtitle:'Mary Shelley',file:'/library/frankenstein/index.html',kind:'html',source:'https://www.gutenberg.org/ebooks/84',note:'Complete public-domain novel.'},
{id:'alice',title:'Alice in Wonderland',subtitle:'Lewis Carroll',file:'/library/alice/index.html',kind:'html',source:'https://www.gutenberg.org/ebooks/11',note:'Complete public-domain novel.'},
{id:'flatland',title:'Flatland',subtitle:'Edwin A. Abbott',file:'/library/flatland/index.html',kind:'html',source:'https://www.gutenberg.org/ebooks/201',note:'Complete illustrated public-domain novel about dimensions.'},
{id:'origin',title:'On the Origin of Species',subtitle:'Charles Darwin · 1859 first edition',file:'/library/origin/index.html',kind:'html',source:'https://www.gutenberg.org/ebooks/1228',note:'Complete historical first edition; modern evolutionary science has developed beyond this text.'}
];

