'use client';
import {useEffect,useState} from 'react';
import {BODY_ROLES,ROLE_LABELS,DEFAULT_PHYSICS,applyPhysics,type PhysicsSettings,type BodyRole} from './physics';
type Selected={id:string;name:string;role:BodyRole;scale:number;position:number[];rotation:number[]};
export function PhysicsPanel(){const [settings,setSettings]=useState<PhysicsSettings>(DEFAULT_PHYSICS),[selected,setSelected]=useState<Selected|null>(null),[entities,setEntities]=useState<{id:string;name:string;role:BodyRole}[]>([]),[controlled,setControlled]=useState<string|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('triptotropic.physics.v1')||'null');if(saved)setSettings(applyPhysics(saved));}catch{}const state=(e:Event)=>{const d=(e as CustomEvent).detail;setSelected(d.selected);setEntities(d.entities);setControlled(d.controlled);setNotice(d.notice);};window.addEventListener('trip-entity-state',state);return()=>window.removeEventListener('trip-entity-state',state);},[]);
 useEffect(()=>{const send=()=>{applyPhysics(settings);window.dispatchEvent(new CustomEvent('trip-physics-settings',{detail:settings}));document.querySelectorAll('iframe').forEach(frame=>{try{if(new URL(frame.src,location.href).origin===location.origin)frame.contentWindow?.postMessage({type:'triptotropic-physics',physics:settings},location.origin);}catch{}});};send();try{localStorage.setItem('triptotropic.physics.v1',JSON.stringify(settings));}catch{}window.addEventListener('trip-physics-ready',send);return()=>window.removeEventListener('trip-physics-ready',send);},[settings]);
 const edit=(d:unknown)=>window.dispatchEvent(new CustomEvent('trip-entity-edit',{detail:d}));
 return <><section className="world-tool-section"><h3>One world · one rulebook</h3><label>Gravity <input aria-label="Gravity" type="number" min="-30" max="50" step=".1" value={settings.gravity} onChange={e=>setSettings({...settings,gravity:+e.target.value})}/> m/s²</label><div className="world-button-grid">{[['Earth',9.81],['Moon',1.62],['Zero G',0],['Reverse',-4]].map(([name,g])=><button key={name} onClick={()=>setSettings({...settings,gravity:+g})}>{name}</button>)}</div><label>Bounce <input type="range" min="0" max="1" step=".05" value={settings.bounce} onChange={e=>setSettings({...settings,bounce:+e.target.value})}/></label><label>Friction <input type="range" min="0" max="1" step=".05" value={settings.friction} onChange={e=>setSettings({...settings,friction:+e.target.value})}/></label><label><input type="checkbox" checked={settings.selecting} onChange={e=>setSettings({...settings,selecting:e.target.checked})}/> Select models by clicking them</label></section>
 <section className="world-tool-section"><h3>Selected model</h3><select aria-label="Select spawned model" value={selected?.id||''} onChange={e=>window.dispatchEvent(new CustomEvent('trip-entity-select',{detail:{id:e.target.value}}))}><option value="">Choose one of {entities.length} objects</option>{entities.map(e=><option key={e.id} value={e.id}>{e.name} · {e.id}</option>)}</select>{selected?<><p><b>{selected.name}</b></p><div className="world-button-grid">{BODY_ROLES.map(role=><button key={role} aria-pressed={selected.role===role} onClick={()=>edit({role})}>{ROLE_LABELS[role]}</button>)}</div><label>Size · {selected.scale.toFixed(2)}×<input aria-label="Model size" type="range" min=".05" max="20" step=".05" value={selected.scale} onChange={e=>edit({scale:+e.target.value})}/></label><div className="world-button-grid"><button onClick={()=>edit({scale:selected.scale*.5})}>Half size</button><button onClick={()=>edit({scale:1})}>Original size</button><button onClick={()=>edit({scale:selected.scale*2})}>Double size</button></div>{(['position','rotation'] as const).map(type=><fieldset key={type}><legend>{type==='position'?'Position':'Rotation (degrees)'}</legend>{['X','Y','Z'].map((axis,i)=><label key={axis}>{axis}<input aria-label={`${type} ${axis}`} type="number" step={type==='position'?.25:15} value={Number((selected[type][i]*(type==='rotation'?180/Math.PI:1)).toFixed(2))} onChange={event=>{const values=[...selected[type]];values[i]=+event.target.value*(type==='rotation'?Math.PI/180:1);edit({[type]:values});}}/></label>)}</fieldset>)}<button onClick={()=>window.dispatchEvent(new Event('trip-entity-delete'))}>Remove selected model</button></>:<p>Spawn something, then choose it here or enable click selection.</p>}</section>
 <section className="world-tool-section"><h3>{controlled?'Controlling '+controlled:'Play & experiment'}</h3><p>WASD moves and turns through 360°. Space jumps; vehicles rise with Space and descend with Q. E picks up. F fires or throws in the direction your model faces.</p><div className="world-button-grid">{[['pickup','Pick up / drop'],['throw','Throw / fire'],['jump','Jump'],['release','Release control']].map(([action,label])=><button key={action} onClick={()=>window.dispatchEvent(new CustomEvent('trip-world-action',{detail:action}))}>{label}</button>)}</div><p role="status">{notice}</p></section>
 <section className="world-tool-section"><h3>Save for the world builder</h3><button onClick={()=>window.dispatchEvent(new Event('trip-world-export'))}>Save scene file</button><label>Load scene file<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(file)try{window.dispatchEvent(new CustomEvent('trip-world-import',{detail:JSON.parse(await file.text())}));}catch{setNotice('That file could not be read.');}}}/></label><small>Scene files keep asset IDs, roles, sizes, positions, rotations and physics settings.</small></section></>;
}
