import * as T from 'three';
import {SITE_ASSETS,type SiteAsset} from '../lib/assetRegistry';
import {buildAsset,type ModelHandle} from './assetFactory';
import {physics,applyPhysics,BODY_ROLES,type BodyRole,WORLD_FORMAT_VERSION} from './physics';
import {collide,type Solid} from '../brain-room/lib/level';
import {Ragdoll} from '../brain-room/lib/ragdoll';
export type WorldEntity={id:string;asset:SiteAsset;root:T.Group;model:ModelHandle;velocity:T.Vector3;role:BodyRole;scale:number;radius:number;half:T.Vector3;bottom:number;grounded:boolean;rag?:Ragdoll;age:number;home:T.Vector3;generation:number};
type ActorFrame={position:T.Vector3;quaternion:T.Quaternion;hand:T.Vector3;radius:number};
type Options={groundAt?:(x:number,z:number)=>number;externalActor?:()=>ActorFrame|null;solids?:Solid[];spawnPoint?:()=>T.Vector3;ground?:number;bounds?:number;onImpact?:(entity:WorldEntity,speed:number)=>void;onControl?:(entity:WorldEntity|null)=>void};
const emit=(name:string,detail:unknown)=>{if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent(name,{detail}));};
export class WorldSimulation{
 entities:WorldEntity[]=[];selected:WorldEntity|null=null;controlled:WorldEntity|null=null;held:WorldEntity|null=null;keys=new Set<string>();notice='Select a model in Physics';time=0;private disposed=false;private paused=false;private selectionBox=new T.BoxHelper(new T.Object3D(),0xd392ff);private sequence=0;private accumulator=0;private queue=Promise.resolve();private listeners:[string,EventListener][]=[];private ray=new T.Raycaster();private start={x:0,y:0};private pending=0;
 constructor(public scene:T.Scene,public camera:T.Camera,public canvas:HTMLElement,public options:Options={}){
 this.scene.add(this.selectionBox);this.selectionBox.visible=false;
 const listen=(name:string,fn:EventListener)=>{window.addEventListener(name,fn);this.listeners.push([name,fn]);};
 listen('trip-library-state',e=>{this.paused=Boolean((e as CustomEvent).detail);this.keys.clear();});listen('trip-world-spawn',e=>{e.preventDefault();const id=(e as CustomEvent).detail.kind;void this.spawn(id);});listen('trip-world-clear',()=>this.clear());listen('trip-physics-settings',e=>applyPhysics((e as CustomEvent).detail));listen('trip-entity-edit',e=>{if(this.selected)void this.edit(this.selected,(e as CustomEvent).detail);});listen('trip-entity-select',e=>this.select(this.entities.find(x=>x.id===(e as CustomEvent).detail.id)||null));listen('trip-entity-delete',()=>{if(this.selected)this.remove(this.selected);});listen('trip-world-export',()=>this.export());listen('trip-world-import',e=>void this.import((e as CustomEvent).detail));listen('trip-world-action',e=>this.action((e as CustomEvent).detail));
 listen('keydown',(e)=>{const k=e as KeyboardEvent;if((k.target as HTMLElement)?.closest('input,textarea,select,[contenteditable]'))return;if(this.controlled&&['KeyW','KeyA','KeyS','KeyD','Space','KeyQ','KeyE','KeyF','ShiftLeft'].includes(k.code)){k.preventDefault();this.keys.add(k.code);if(!k.repeat){if(k.code==='KeyE')this.pickup();if(k.code==='KeyF')this.fire();if(k.code==='Space'&&this.controlled.grounded){this.controlled.velocity.y=6;this.controlled.grounded=false;}}}});listen('trip-world-stick',e=>{const d=(e as CustomEvent).detail;for(const [k,on] of [['KeyA',d.x<-.15],['KeyD',d.x>.15],['KeyW',d.z<-.15],['KeyS',d.z>.15]] as [string,boolean][]){if(on)this.keys.add(k);else this.keys.delete(k);}});listen('keyup',e=>this.keys.delete((e as KeyboardEvent).code));listen('blur',()=>this.keys.clear());
 canvas.addEventListener('pointerdown',this.down);canvas.addEventListener('pointerup',this.up);emit('trip-physics-ready',null);this.report();
 }
 private down=(e:PointerEvent)=>{this.start={x:e.clientX,y:e.clientY};};
 private up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-this.start.x,e.clientY-this.start.y)>7)return;const rect=this.canvas.getBoundingClientRect();this.ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),this.camera);const hit=this.ray.intersectObjects(this.entities.map(e=>e.rag?.root||e.root),true)[0];if(!hit)return;let book:T.Object3D|null=hit.object;while(book&&!book.userData.bookId)book=book.parent;if(book&&!physics.selecting){emit('trip-library-open',book.userData.bookId);return;}if(!physics.selecting)return;const entity=this.entities.find(e=>{let o:T.Object3D|null=hit.object;while(o){if(o===e.root||o===e.rag?.root)return true;o=o.parent;}return false;});this.select(entity||null);};
 select(entity:WorldEntity|null){this.selected=entity;this.report();}
 report(){const e=this.selected;emit('trip-entity-state',{selected:e?{id:e.id,name:e.asset.label,assetId:e.asset.id,role:e.role,scale:e.scale,position:e.rag?e.rag.center().toArray():e.root.position.toArray(),rotation:[e.root.rotation.x,e.root.rotation.y,e.root.rotation.z]}:null,entities:this.entities.map(x=>({id:x.id,name:x.asset.label,role:x.role})),controlled:this.controlled?.asset.label||null,notice:this.notice});}
 async spawn(id:string,role:BodyRole='holdable',position?:T.Vector3){id=({baboon:'baboogoo',gorilla:'mongo',chimpanzee:'gongo',yeti:'yongo001'} as Record<string,string>)[id]||id;const asset=SITE_ASSETS.find(a=>a.id===id);if(!asset){this.notice='Asset not found: '+id;this.report();return;}if(this.entities.length+this.pending>=150){this.notice='150 objects in this scene. Clear or remove some before spawning more.';this.report();return;}this.pending++;try{const model=await buildAsset(asset);if(this.disposed){model.dispose?.();return;}const root=new T.Group();root.add(model.root);const bounds=new T.Box3().setFromObject(model.root),center=bounds.getCenter(new T.Vector3());model.root.position.sub(center);root.position.copy(position||this.options.spawnPoint?.()||new T.Vector3((Math.random()-.5)*9,3,(Math.random()-.5)*9));this.scene.add(root);const size=bounds.getSize(new T.Vector3());const entity:WorldEntity={id:'entity-'+(++this.sequence),asset,root,model,velocity:new T.Vector3(),role:'holdable',scale:1,radius:Math.max(.08,Math.max(size.x,size.z)*.4),half:size.multiplyScalar(.5),bottom:-size.y,grounded:false,age:0,home:root.position.clone(),generation:0};this.entities.push(entity);await this.setRole(entity,role);this.select(entity);return entity;}catch(error){this.notice='Could not load '+asset.label+': '+String(error);this.report();}finally{this.pending--;}}
 async setRole(e:WorldEntity,role:BodyRole){if(!BODY_ROLES.includes(role))return;if(e.rag){const position=e.rag.center(),generation=++e.generation;const model=await buildAsset(e.asset);if(this.disposed||generation!==e.generation||!this.entities.includes(e)){model.dispose?.();return;}e.rag.root.removeFromParent();e.model.dispose?.();e.rag=undefined;e.root.clear();e.model=model;const box=new T.Box3().setFromObject(model.root),center=box.getCenter(new T.Vector3());model.root.position.sub(center);e.root.add(model.root);e.root.visible=true;e.root.scale.setScalar(e.scale);e.root.position.copy(position);}
 e.role=role;e.velocity.set(0,0,0);if(this.controlled===e&&!['playable','vehicle','weapon'].includes(role)){this.controlled=null;this.options.onControl?.(null);}if(['playable','vehicle','weapon'].includes(role)){this.controlled=e;this.options.onControl?.(e);}if(role==='ragdoll'){e.root.updateMatrixWorld(true);e.rag=new Ragdoll(e.root,this.scene,new T.Vector3(0,1,0));}this.report();}
 async edit(e:WorldEntity,d:{role?:BodyRole;scale?:number;position?:number[];rotation?:number[]}){if(d.role)await this.setRole(e,d.role);if(Number.isFinite(d.scale)){const next=T.MathUtils.clamp(d.scale!,.05,20),wasRag=e.role==='ragdoll';if(wasRag)await this.setRole(e,'holdable');e.scale=next;e.root.scale.setScalar(next);if(wasRag)await this.setRole(e,'ragdoll');}if(d.position?.length===3&&d.position.every(Number.isFinite)){if(e.rag){const delta=new T.Vector3(...d.position as [number,number,number]).sub(e.rag.center());e.rag.nodes.forEach(n=>{n.p.add(delta);n.previous.add(delta);});}else e.root.position.fromArray(d.position);}if(d.rotation?.length===3&&d.rotation.every(Number.isFinite)){if(e.rag){const center=e.rag.center(),q=new T.Quaternion().setFromEuler(new T.Euler(...d.rotation as [number,number,number])).multiply(e.root.quaternion.clone().invert());e.rag.nodes.forEach(n=>{n.p.sub(center).applyQuaternion(q).add(center);n.previous.sub(center).applyQuaternion(q).add(center);});}e.root.rotation.set(...d.rotation as [number,number,number]);}this.report();}
 actorFrame():ActorFrame|null{const a=this.controlled;if(!a)return this.options.externalActor?.()||null;return {position:a.root.position,quaternion:a.root.quaternion,radius:a.radius*a.scale,hand:a.root.position.clone().add(new T.Vector3(a.radius*.7,a.half.y*.3,a.radius+.65).multiplyScalar(a.scale).applyQuaternion(a.root.quaternion))};}
 pickup(){const frame=this.actorFrame();if(!frame)return;if(this.held){this.held.rag?.release();this.held=null;return;}const p=frame.position;this.held=this.entities.filter(e=>e!==this.controlled&&(e.rag?e.rag.center():e.root.position).distanceTo(p)<3+e.radius).sort((a,b)=>a.root.position.distanceToSquared(p)-b.root.position.distanceToSquared(p))[0]||null;this.notice=this.held?'Holding '+this.held.asset.label:'Nothing close enough';this.report();}
 fire(){const actor=this.controlled,frame=this.actorFrame();if(!frame)return;const direction=new T.Vector3(0,0,1).applyQuaternion(frame.quaternion);if(this.held){const held=this.held;if(held.rag){held.rag.release();for(const node of held.rag.nodes)node.previous.copy(node.p).addScaledVector(direction,-18/60).add(new T.Vector3(0,-3/60,0));this.held=null;this.report();return;}held.velocity.copy(direction).multiplyScalar(18);held.velocity.y+=3;held.role='holdable';this.held=null;this.notice='Thrown in the direction you are facing';this.report();return;}const shoot=actor?.model.root.userData.fire;if(typeof shoot==='function')shoot();const ammo=this.entities.find(e=>e.role==='ammo');void this.spawn(ammo?.asset.id||'ammo','ammo',frame.position.clone().addScaledVector(direction,frame.radius+.8)).then(shot=>{if(shot){shot.velocity.copy(direction).multiplyScalar(28);shot.velocity.y+=.5;shot.age=20;this.notice='Fired';this.report();}});}
 action(action:string){if(action==='pickup')this.pickup();if(action==='fire'||action==='throw')this.fire();if(action==='release'){this.controlled=null;this.options.onControl?.(null);this.report();}if(action==='jump'&&this.controlled?.grounded)this.controlled.velocity.y=6;}
 update(dt:number){this.selectionBox.visible=physics.selecting&&!!this.selected;if(this.selected)this.selectionBox.setFromObject(this.selected.rag?.root||this.selected.root);if(this.paused)return;this.accumulator+=Math.min(.1,dt);while(this.accumulator>=1/60){this.tick(1/60);this.accumulator-=1/60;}for(const e of this.entities)if(!e.rag)e.model.update?.(this.time,dt,e.velocity.lengthSq()>.1);}
 private tick(dt:number){this.time+=dt;const defaultFloor=this.options.ground??.34,bounds=this.options.bounds??90;const solids=this.options.solids||[{center:new T.Vector3(0,defaultFloor-.5,0),half:new T.Vector3(bounds,.5,bounds)}];for(const e of [...this.entities]){const floor=this.options.groundAt?.(e.root.position.x,e.root.position.z)??defaultFloor;e.age+=dt;if(e.rag){if(e===this.held&&this.actorFrame()){e.rag.grabbed=0;e.rag.target.copy(this.actorFrame()!.hand);}e.rag.step(dt,solids);continue;}if(e===this.held&&this.actorFrame()){const actor=this.actorFrame()!;e.root.position.copy(actor.hand);e.root.quaternion.copy(actor.quaternion);e.velocity.set(0,0,0);continue;}if(e.role==='decoration')continue;if(e.role==='display'){e.root.rotation.y+=dt*.25;continue;}const active=e===this.controlled,moving=active&&(this.keys.has('KeyW')||this.keys.has('KeyA')||this.keys.has('KeyS')||this.keys.has('KeyD'));if(active){const x=Number(this.keys.has('KeyD'))-Number(this.keys.has('KeyA')),z=Number(this.keys.has('KeyS'))-Number(this.keys.has('KeyW'));const speed=e.role==='vehicle'?8:4.4;e.velocity.x+=(x*speed-e.velocity.x)*Math.min(1,dt*10);e.velocity.z+=(z*speed-e.velocity.z)*Math.min(1,dt*10);if(moving)e.root.rotation.y=Math.atan2(x,z);if(e.role==='vehicle'){if(this.keys.has('Space'))e.velocity.y+=physics.gravity*dt+6*dt;if(this.keys.has('KeyQ'))e.velocity.y-=6*dt;}}
 else if(e.role==='npc'){const a=this.time*.3+Number(e.id.split('-')[1])*1.7;e.velocity.x=Math.cos(a)*1.3;e.velocity.z=Math.sin(a*.7)*1.3;e.root.rotation.y=Math.atan2(e.velocity.x,e.velocity.z);if(e.root.position.distanceTo(e.home)>10){const back=e.home.clone().sub(e.root.position).normalize();e.velocity.x=back.x*2;e.velocity.z=back.z*2;}}
 const speed=e.velocity.length(),steps=Math.max(1,Math.min(16,Math.ceil(speed*dt/.15)));for(let i=0;i<steps;i++){const h=dt/steps;e.velocity.y-=physics.gravity*h;e.root.position.addScaledVector(e.velocity,h);this.options.onImpact?.(e,speed);const radius=e.radius*e.scale;e.grounded=collide(e.root.position,radius,solids,e.velocity,physics.bounce);const bottom=e.half.y*e.scale;if(e.root.position.y<floor+bottom&&physics.gravity>=0){e.root.position.y=floor+bottom;e.velocity.y=Math.abs(e.velocity.y)>1?Math.abs(e.velocity.y)*physics.bounce:0;e.grounded=true;}if(e.grounded&&!active){const f=Math.exp(-physics.friction*7*h);e.velocity.x*=f;e.velocity.z*=f;}}
 for(const axis of ['x','z'] as const)if(Math.abs(e.root.position[axis])>bounds){e.root.position[axis]=T.MathUtils.clamp(e.root.position[axis],-bounds,bounds);e.velocity[axis]*=-physics.bounce;}if(Math.abs(e.root.position.y)>150){e.root.position.copy(e.home);e.velocity.set(0,0,0);}if(e.role==='ammo'&&e.age>35)this.remove(e);}
 for(let a=0;a<this.entities.length;a++)for(let b=a+1;b<this.entities.length;b++){const A=this.entities[a],B=this.entities[b];if(A.rag||B.rag||A===this.held||B===this.held||['display','decoration'].includes(A.role)||['display','decoration'].includes(B.role))continue;const d=B.root.position.clone().sub(A.root.position),length=d.length(),r=A.radius*A.scale+B.radius*B.scale;if(length>.001&&length<r){d.divideScalar(length);A.root.position.addScaledVector(d,-(r-length)*.5);B.root.position.addScaledVector(d,(r-length)*.5);const speed=B.velocity.clone().sub(A.velocity).dot(d);if(speed<0){A.velocity.addScaledVector(d,speed*(1+physics.bounce)*.5);B.velocity.addScaledVector(d,-speed*(1+physics.bounce)*.5);}}}}
 followCamera(){if(!this.controlled)return;const focus=this.controlled.root.position,desired=focus.clone().add(new T.Vector3(0,3,7));this.camera.position.lerp(desired,.07);this.camera.lookAt(focus);}
 remove(e:WorldEntity){e.generation++;e.rag?.root.removeFromParent();e.root.removeFromParent();e.model.dispose?.();this.entities=this.entities.filter(x=>x!==e);if(this.selected===e)this.selected=null;if(this.controlled===e){this.controlled=null;this.options.onControl?.(null);}if(this.held===e)this.held=null;this.report();}
 clear(){[...this.entities].forEach(e=>this.remove(e));}
 serialize(){return{format:'triptotropic-world',version:WORLD_FORMAT_VERSION,physics:{...physics},entities:this.entities.map(e=>({assetId:e.asset.id,role:e.role,scale:e.scale,position:(e.rag?e.rag.center():e.root.position).toArray(),rotation:[e.root.rotation.x,e.root.rotation.y,e.root.rotation.z]}))};}
 export(){const url=URL.createObjectURL(new Blob([JSON.stringify(this.serialize(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='triptotropic-world.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async import(data:ReturnType<WorldSimulation['serialize']>){if(data?.format!=='triptotropic-world'||data.version!==1||!Array.isArray(data.entities)){this.notice='This is not a supported world file';this.report();return;}this.clear();applyPhysics(data.physics||{});for(const d of data.entities.slice(0,150)){if(!Array.isArray(d.position)||!d.position.every(Number.isFinite))continue;const e=await this.spawn(d.assetId,'holdable',new T.Vector3(...d.position as [number,number,number]));if(e)await this.edit(e,d);}this.report();}
 dispose(){this.disposed=true;this.clear();this.selectionBox.removeFromParent();this.selectionBox.geometry.dispose();(this.selectionBox.material as T.Material).dispose();this.listeners.forEach(([name,fn])=>window.removeEventListener(name,fn));this.canvas.removeEventListener('pointerdown',this.down);this.canvas.removeEventListener('pointerup',this.up);}
}
