import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {DatabaseSync} from 'node:sqlite';
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.gif':'image/gif','.pdf':'application/pdf','.glb':'model/gltf-binary','.wasm':'application/wasm','.woff2':'font/woff2','.mp3':'audio/mpeg','.mp4':'video/mp4','.fbx':'application/octet-stream'};
export async function startOffline(siteDir,dataDir,port=43169){fs.mkdirSync(dataDir,{recursive:true});const sql=new DatabaseSync(path.join(dataDir,'triptotropic.sqlite'));sql.exec('PRAGMA journal_mode=WAL');const migration=fs.readFileSync(path.join(siteDir,'drizzle/0000_nebulous_cammi.sql'),'utf8').replace(/CREATE TABLE (?!IF NOT EXISTS )/g,'CREATE TABLE IF NOT EXISTS ').replace(/CREATE UNIQUE INDEX (?!IF NOT EXISTS )/g,'CREATE UNIQUE INDEX IF NOT EXISTS ').replace(/CREATE INDEX (?!IF NOT EXISTS )/g,'CREATE INDEX IF NOT EXISTS ');sql.exec(migration);
 const adapt=(query,params=[])=>({bind(...values){return adapt(query,values)},async all(){const rows=sql.prepare(query).all(...params);return {success:true,results:rows,meta:{changes:0}}},async raw(options){const stmt=sql.prepare(query),rows=stmt.all(...params),names=stmt.columns().map(c=>c.name);return [...(options?.columnNames?[names]:[]),...rows.map(row=>names.map(k=>row[k]))]},async first(column){const row=sql.prepare(query).get(...params);return column?row?.[column]??null:row??null},async run(){const result=sql.prepare(query).run(...params);return {success:true,results:[],meta:{changes:Number(result.changes),last_row_id:Number(result.lastInsertRowid)}}}});
 const DB={prepare:query=>adapt(query),async batch(statements){sql.exec('BEGIN');try{const rows=[];for(const s of statements)rows.push(await s.all());sql.exec('COMMIT');return rows;}catch(e){sql.exec('ROLLBACK');throw e;}},async exec(query){sql.exec(query);return {count:0,duration:0}}};globalThis.__TRIP_OFFLINE_DB__=DB;process.env.OPENAI_API_KEY='';
 // The desktop app deliberately uses local Bongo replies and archived social cards.
 const worker=(await import(pathToFileURL(path.join(siteDir,'dist/server/index.js')).href)).default;
 const roots=[path.join(siteDir,'dist/client'),path.join(siteDir,'public')];
 const asset=async request=>{let pathname;try{pathname=decodeURIComponent(new URL(request.url).pathname);}catch{return new Response('Invalid path',{status:400})}for(const root of roots){let file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)&&file!==root)continue;try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.statSync(file).isFile())continue;const data=fs.readFileSync(file),headers={'Content-Type':MIME[path.extname(file).toLowerCase()]||'application/octet-stream','Cache-Control':'no-cache','Accept-Ranges':'bytes'};const range=request.headers.get('range')?.match(/^bytes=(\d+)-(\d*)$/);if(range){const first=Number(range[1]),last=Math.min(data.length-1,range[2]?Number(range[2]):data.length-1);if(first>last)return new Response(null,{status:416});headers['Content-Range']=`bytes ${first}-${last}/${data.length}`;return new Response(data.subarray(first,last+1),{status:206,headers});}return new Response(request.method==='HEAD'?null:data,{headers});}catch{}}return new Response('Not found',{status:404});};
 const server=http.createServer(async(req,res)=>{try{const origin=`http://127.0.0.1:${server.address().port}`;if(req.headers.origin&&req.headers.origin!==origin){res.writeHead(403);res.end('Local app only');return;}const body=[];let bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>4_000_000){res.writeHead(413);res.end('Request too large');return;}body.push(chunk);}const request=new Request(origin+req.url,{method:req.method,headers:req.headers,...(body.length?{body:Buffer.concat(body)}:{})});let response;if(new URL(request.url).pathname==='/api/social-feed'){const feed=JSON.parse(fs.readFileSync(path.join(siteDir,'public/anubis-room/social-posts.json'),'utf8'));response=Response.json(feed);}else{const u=new URL(request.url);const imagePath=['/_vinext/image','/_next/image'].includes(u.pathname)?u.searchParams.get('url'):null;response=await asset(imagePath?.startsWith('/')&&!imagePath.startsWith('//')?new Request(new URL(imagePath,origin)):request);if(response.status===404)response=await worker.fetch(request,{ASSETS:{fetch:asset},DB},{waitUntil:p=>p.catch(()=>{}),passThroughOnException(){}});}const headers=Object.fromEntries(response.headers);const cookies=response.headers.getSetCookie();if(cookies.length)headers['set-cookie']=cookies;res.writeHead(response.status,headers);res.end(Buffer.from(await response.arrayBuffer()));}catch(error){res.writeHead(500,{'Content-Type':'text/plain'});res.end('The local app encountered an error. See Data/app.log.');fs.appendFileSync(path.join(dataDir,'app.log'),new Date().toISOString()+' '+String(error.stack||error)+'\n');}});
 await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve);});return {url:`http://127.0.0.1:${server.address().port}`,close:()=>{server.close();sql.close();}};
}
if(process.argv.includes('--serve')){const site=path.resolve(process.argv[process.argv.indexOf('--serve')+1]||'.'),data=path.resolve(process.argv[process.argv.indexOf('--serve')+2]||'work/offline-data');const app=await startOffline(site,data,0);console.log(app.url);}

